obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone-tddi.o
chipone-tddi-y += cts_driver.o
chipone-tddi-y += cts_core.o
chipone-tddi-y += cts_sfctrlv2.o
chipone-tddi-y += cts_spi_flash.o
chipone-tddi-y += cts_firmware.o
chipone-tddi-y += cts_test.o
chipone-tddi-y += cts_charger_detect.o
chipone-tddi-y += cts_earjack_detect.o
chipone-tddi-y += cts_tcs.o
chipone-tddi-y += cts_platform.o
chipone-tddi-y += cts_tool.o
chipone-tddi-y += cts_sysfs.o
chipone-tddi-y += cts_strerror.o
chipone-tddi-y += cts_oem.o

